apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jenkinsApplicationName }}
  namespace: {{ .Values.namespace }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.jenkinsApplicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.jenkinsApplicationName }}
    spec:
      containers:
        - name: {{ .Values.jenkinsApplicationName }}
          image: "{{ .Values.jenkinsimage.name }}:{{ .Values.jenkinsimage.tag }}"
          resources: 
            requests: 
              memory: "512"
              cpu: "500m" 
            limits: 
              memory: "1Gi" 
              cpu: "500m"
          ports:
            - containerPort: 8080
